export { default as Hero }     from './Hero'
export { default as Services } from './Services'
export { default as Projects } from './Projects'
export { default as WhyUs }    from './WhyUs'
export { default as FAQ }      from './FAQ'
export { default as Contact }  from './Contact'
